name: test
on:
  push:
    branches: ["dev"]
jobs:
  release:
    name: Check status
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          command: "echo hello world"

