name: test
on:
  push:
    branches: ["dev"]
jobs:

  test:
    name: Check status
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          command: "hiuiue"
  release:  
    name: Check sta
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          command: "echo hello world"
